### ISSUE TITLE
Getting SSLException

### ISSUE THREAD

**Issue by gmarshall56** [escline/InstallCert#14]
Compiled (java 8). Then ran with:
`java InstallCert localhost:3000`

Getting:
javax.net.ssl.SSLException: Unsupported or unrecognized SSL message
        at sun.security.ssl.SSLSocketInputRecord.handleUnknownRecord(SSLSocketInputRecord.java:448)
        at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:174)
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:110)
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1279)
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1188)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:401)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:373)
        at InstallCert.main(InstallCert.java:150)
Could not obtain server certificate chain

Also getting this exception using Java 11...
Thank you

**Comment by escline** [comment]
Looks like the exception relates to whatever you are serving from localhost. Is port 3000 serving SSL? Is there a certificate installed on your server? The exception is telling you "Could not obtain server certificate chain" on your localhost:3000.
