### ISSUE TITLE
Not working in JDK7

### ISSUE THREAD

**Issue by ashokpalukuri** [escline/InstallCert#5]
trying to install cert in jdk7, getting the following Exception 

javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.recvAlert(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at com.imagework.utils.DomainCertificate.installSSLCert(DomainCertificate.java:85)
	at com.imagework.utils.XAPIUtils.getAndInstallSSLCert(XAPIUtils.java:269)

**Comment by escline** [comment]
Verified working with JDK8 on Windows.
