### ISSUE TITLE
java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

### ISSUE THREAD

**Issue by prayagupa** [escline/InstallCert#8]
Following steps dont work in windows, (Works in mac even without keytool import). Might not be related to `InstallCert.java` but java installation on windows itself. 

```bash
git clone https://github.com/escline/InstallCert
javac InstallCert.java
java InstallCert endpoint.com:443

cp jssecacerts $JAVA_HOME/jre/lib/security # was enough on Mac Unix OS

# or following maybe for windows - https://stackoverflow.com/a/32074827/432903

keytool -exportcert -alias endpoint.com-1 -keystore jssecacerts -storepass changeit -file endpoint.com.cert
keytool -importcert -alias endpoint.com -keystore $JAVA_HOME/jre/lib/security/cacerts -storepass changeit -file endpoint.com.cert
```

error
-------

```bash
[info] Running GetAuthenticationToken
[error] (run-main-0) java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        at sun.security.ssl.Handshaker.checkThrown(Unknown Source)
        at sun.security.ssl.SSLEngineImpl.checkTaskThrown(Unknown Source)
        at sun.security.ssl.SSLEngineImpl.readNetRecord(Unknown Source)
        at sun.security.ssl.SSLEngineImpl.unwrap(Unknown Source)
        at javax.net.ssl.SSLEngine.unwrap(Unknown Source)
        at akka.stream.impl.io.TLSActor.akka$stream$impl$io$TLSActor$$doUnwrap(TLSActor.scala:388)
        at akka.stream.impl.io.TLSActor.akka$stream$impl$io$TLSActor$$doInbound(TLSActor.scala:311)
        at akka.stream.impl.io.TLSActor$$anonfun$1.apply$mcV$sp(TLSActor.scala:247)
        at akka.stream.impl.Pump$class.pump(Transfer.scala:199)
        at akka.stream.impl.io.TLSActor.pump(TLSActor.scala:49)
        at akka.stream.impl.BatchingInputBuffer.enqueueInputElement(ActorProcessor.scala:90)
        at akka.stream.impl.BatchingInputBuffer$$anonfun$upstreamRunning$1.applyOrElse(ActorProcessor.scala:141)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
        at akka.stream.impl.SubReceive.apply(Transfer.scala:16)
        at akka.stream.impl.FanIn$InputBunch$$anonfun$subreceive$1.applyOrElse(FanIn.scala:234)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
        at akka.stream.impl.SubReceive.apply(Transfer.scala:16)
        at akka.stream.impl.SubReceive.apply(Transfer.scala:12)
        at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
        at akka.stream.impl.SubReceive.applyOrElse(Transfer.scala:12)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
        at akka.stream.impl.io.TLSActor.aroundReceive(TLSActor.scala:49)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        at sun.security.validator.PKIXValidator.<init>(Unknown Source)
        at sun.security.validator.Validator.getInstance(Unknown Source)
        at sun.security.ssl.X509TrustManagerImpl.getValidator(Unknown Source)
        at sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(Unknown Source)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
        at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
        at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
        at sun.security.ssl.Handshaker.processLoop(Unknown Source)
        at sun.security.ssl.Handshaker$1.run(Unknown Source)
        at sun.security.ssl.Handshaker$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.security.ssl.Handshaker$DelegatedTask.run(Unknown Source)
        at akka.stream.impl.io.TLSActor.runDelegatedTasks(TLSActor.scala:423)
        at akka.stream.impl.io.TLSActor.akka$stream$impl$io$TLSActor$$doUnwrap(TLSActor.scala:392)
        at akka.stream.impl.io.TLSActor.akka$stream$impl$io$TLSActor$$doInbound(TLSActor.scala:311)
        at akka.stream.impl.io.TLSActor$$anonfun$1.apply$mcV$sp(TLSActor.scala:247)
        at akka.stream.impl.Pump$class.pump(Transfer.scala:199)
        at akka.stream.impl.io.TLSActor.pump(TLSActor.scala:49)
        at akka.stream.impl.BatchingInputBuffer.enqueueInputElement(ActorProcessor.scala:90)
        at akka.stream.impl.BatchingInputBuffer$$anonfun$upstreamRunning$1.applyOrElse(ActorProcessor.scala:141)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
        at akka.stream.impl.SubReceive.apply(Transfer.scala:16)
        at akka.stream.impl.FanIn$InputBunch$$anonfun$subreceive$1.applyOrElse(FanIn.scala:234)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
        at akka.stream.impl.SubReceive.apply(Transfer.scala:16)
        at akka.stream.impl.SubReceive.apply(Transfer.scala:12)
        at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
        at akka.stream.impl.SubReceive.applyOrElse(Transfer.scala:12)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
        at akka.stream.impl.io.TLSActor.aroundReceive(TLSActor.scala:49)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        at java.security.cert.PKIXParameters.setTrustAnchors(Unknown Source)
        at java.security.cert.PKIXParameters.<init>(Unknown Source)
        at java.security.cert.PKIXBuilderParameters.<init>(Unknown Source)
        at sun.security.validator.PKIXValidator.<init>(Unknown Source)
        at sun.security.validator.Validator.getInstance(Unknown Source)
        at sun.security.ssl.X509TrustManagerImpl.getValidator(Unknown Source)
        at sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(Unknown Source)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
        at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
        at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
        at sun.security.ssl.Handshaker.processLoop(Unknown Source)
        at sun.security.ssl.Handshaker$1.run(Unknown Source)
        at sun.security.ssl.Handshaker$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.security.ssl.Handshaker$DelegatedTask.run(Unknown Source)
        at akka.stream.impl.io.TLSActor.runDelegatedTasks(TLSActor.scala:423)
        at akka.stream.impl.io.TLSActor.akka$stream$impl$io$TLSActor$$doUnwrap(TLSActor.scala:392)
        at akka.stream.impl.io.TLSActor.akka$stream$impl$io$TLSActor$$doInbound(TLSActor.scala:311)
        at akka.stream.impl.io.TLSActor$$anonfun$1.apply$mcV$sp(TLSActor.scala:247)
        at akka.stream.impl.Pump$class.pump(Transfer.scala:199)
        at akka.stream.impl.io.TLSActor.pump(TLSActor.scala:49)
        at akka.stream.impl.BatchingInputBuffer.enqueueInputElement(ActorProcessor.scala:90)
        at akka.stream.impl.BatchingInputBuffer$$anonfun$upstreamRunning$1.applyOrElse(ActorProcessor.scala:141)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
        at akka.stream.impl.SubReceive.apply(Transfer.scala:16)
        at akka.stream.impl.FanIn$InputBunch$$anonfun$subreceive$1.applyOrElse(FanIn.scala:234)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
        at akka.stream.impl.SubReceive.apply(Transfer.scala:16)
        at akka.stream.impl.SubReceive.apply(Transfer.scala:12)
        at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
        at akka.stream.impl.SubReceive.applyOrElse(Transfer.scala:12)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
        at akka.stream.impl.io.TLSActor.aroundReceive(TLSActor.scala:49)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[trace] Stack trace suppressed: run last compile:run for the full output.
```

**Comment by dragon788** [comment]
There is a trustedStore and a keyStore when dealing with Tomcat and newer versions seem to require both depending on whether you are using the system JRE's cacerts or an application local JRE with it's own cacerts.
